# Generated by Django 4.1.13 on 2024-05-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(choices=[('INTERN', 'INTERN'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR'), ('MANAGEMENT', 'MANAGEMENT')], default='JUNIOR', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('FOZ DO LIZANDRO', 'FOZ DO LIZANDRO'), ('PRAIA DO SUL', 'PRAIA DO SUL'), ('PRAIA DO NORTE', 'PRAIA DO NORTE'), ('MATADURO', 'MATADURO'), ('RIBERA', 'RIBERA')], max_length=50)),
                ('type_of_lesson', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED'), ('PRIVATE', 'PRIVATE')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('CANCELED', 'CANCELED')], default='LIVE', max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.coach')),
            ],
            options={
                'unique_together': {('coach', 'location', 'type_of_lesson', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=50)),
                ('is_regular', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonAttendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
