# Generated by Django 4.1.13 on 2024-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lesson_unique_together_remove_coach_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='participant',
            field=models.ManyToManyField(to='schedule.student'),
        ),
    ]
