# Generated by Django 4.1.13 on 2024-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_lesson_comment_lesson_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='participant',
            field=models.ManyToManyField(blank=True, to='schedule.student'),
        ),
        migrations.DeleteModel(
            name='LessonAttendence',
        ),
    ]
