# Generated by Django 4.1.13 on 2024-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_lesson_participant_delete_lessonattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='number_of_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
