# Generated by Django 4.1.13 on 2024-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_lesson_number_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
